services:
  middleearth-chat:
    build:
      context: .
      dockerfile: docker/Dockerfile
      shm_size: "2gb"
    ports:
      - "3000:3000"
    environment:
      - LOTR_CHARACTERS_API_URL=http://api:8000
      - NODE_ENV=production
    networks:
      - shared_network
    restart: unless-stopped

networks:
  shared_network:
    external: true
